const API_BASE=(window.RAKSHAK_API||localStorage.getItem('rakshak_api')||((location.hostname==='localhost'||location.hostname==='127.0.0.1')?'http://localhost:8000':'')).replace(/\/$/,'');
const state={type:'Accident',lat:null,lng:null,accuracy:null,evidence:null,stream:null,watchId:null,incidentId:null,ws:null};
const $=id=>document.getElementById(id); let incidents=[];
const priorityColor=p=>p==='CRITICAL'?'red':p==='HIGH'?'orange':'yellow';
function renderQueue(){ $('incidentList').innerHTML=incidents.length?incidents.map(x=>`<div class="queue-item"><i class="qdot ${priorityColor(x.priority)}"></i><div class="q-main"><b>${x.type}</b><span>${x.latitude&&x.longitude?`${Number(x.latitude).toFixed(5)}, ${Number(x.longitude).toFixed(5)}`:'Location pending'}</span></div><div class="q-meta"><strong>${x.status||x.priority}</strong><span>${new Date(x.created_at).toLocaleTimeString()}</span></div></div>`).join(''):'<div class="queue-item"><div class="q-main"><b>No live incidents yet</b><span>Reports will appear here.</span></div></div>'; $('activeCount').textContent=incidents.filter(x=>!['RESOLVED','CANCELLED'].includes(x.status)).length; $('criticalCount').textContent=incidents.filter(x=>x.priority==='CRITICAL'&&!['RESOLVED','CANCELLED'].includes(x.status)).length; }
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3000)}
function updateLocation(pos){state.lat=pos.coords.latitude;state.lng=pos.coords.longitude;state.accuracy=pos.coords.accuracy;$('locationText').textContent=`${state.lat.toFixed(6)}, ${state.lng.toFixed(6)} • accuracy ±${Math.round(state.accuracy)}m • LIVE`;if(state.incidentId)fetch(`${API_BASE}/api/incidents/${state.incidentId}/location`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({latitude:state.lat,longitude:state.lng,accuracy:state.accuracy})}).catch(()=>{})}
function getGPS(){ $('locationText').textContent='Requesting precise location…';if(!navigator.geolocation){$('locationText').textContent='Geolocation is not supported by this browser.';return}if(state.watchId!==null)navigator.geolocation.clearWatch(state.watchId);state.watchId=navigator.geolocation.watchPosition(updateLocation,()=>{$('locationText').textContent='Location permission unavailable.';toast('GPS permission was not granted')},{enableHighAccuracy:true,timeout:10000,maximumAge:0});toast('Live GPS tracking enabled')}
function showPreview(file){const box=$('preview');box.innerHTML='';state.evidence=file;const url=URL.createObjectURL(file);const el=file.type.startsWith('video/')?document.createElement('video'):document.createElement('img');el.src=url;if(el.tagName==='VIDEO'){el.controls=true;el.muted=true;el.playsInline=true}box.appendChild(el)}
async function startCamera(){if(!navigator.mediaDevices?.getUserMedia){toast('Live camera is not supported in this browser.');return}try{state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});$('cameraPreview').srcObject=state.stream;$('cameraPlaceholder').style.display='none';$('recordingDot').style.display='block';$('cameraBtn').hidden=true;$('cameraStop').hidden=false;toast('Live camera started')}catch(e){toast('Camera permission was not granted.')}}
function stopCamera(){if(state.stream)state.stream.getTracks().forEach(t=>t.stop());state.stream=null;$('cameraPreview').srcObject=null;$('cameraPlaceholder').style.display='grid';$('recordingDot').style.display='none';$('cameraBtn').hidden=false;$('cameraStop').hidden=true;toast('Live camera stopped')}
async function loadIncidents(){if(!API_BASE){renderQueue();return}try{const r=await fetch(`${API_BASE}/api/incidents`);if(!r.ok)throw Error();incidents=await r.json();renderQueue()}catch(e){toast('API offline — local interface still available.');renderQueue()}}
function connectRealtime(){if(!API_BASE)return;try{state.ws=new WebSocket(`${API_BASE.replace(/^http/,'ws')}/ws`);state.ws.onopen=()=>toast('Command Center real-time link connected');state.ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.incident){const i=incidents.findIndex(x=>x.id===m.incident.id);if(i>=0)incidents[i]=m.incident;else incidents.unshift(m.incident);renderQueue()}};state.ws.onclose=()=>setTimeout(connectRealtime,3000)}catch(e){}}
const DB_NAME='rakshak-offline',DB_VERSION=1;
function openOfflineDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>r.result.createObjectStore('queue',{keyPath:'localId',autoIncrement:true});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function queueOffline(payload,file){try{const db=await openOfflineDB();await new Promise((resolve,reject)=>{const tx=db.transaction('queue','readwrite');tx.objectStore('queue').add({payload,file:file||null,queued_at:new Date().toISOString()});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();toast('No internet: emergency saved securely on this device and will retry automatically.');return true}catch(e){toast('Offline save failed. Keep the evidence and retry when connected.');return false}}
async function flushOffline(){if(!API_BASE||!navigator.onLine)return;let db;try{db=await openOfflineDB();const items=await new Promise((resolve,reject)=>{const tx=db.transaction('queue','readonly'),q=tx.objectStore('queue').getAll();q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)});for(const item of items){try{const r=await fetch(`${API_BASE}/api/incidents`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(item.payload)});if(!r.ok)continue;const incident=await r.json();if(item.file){const fd=new FormData();fd.append('file',item.file,item.file.name||'evidence');const er=await fetch(`${API_BASE}/api/incidents/${incident.id}/evidence`,{method:'POST',body:fd});if(!er.ok)continue}await new Promise((resolve,reject)=>{const tx=db.transaction('queue','readwrite');tx.objectStore('queue').delete(item.localId);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});toast(`Offline emergency ${incident.id} uploaded successfully.`)}catch(e){break}}db.close()}catch(e){if(db)try{db.close()}catch(_){}}}
async function sendReport(){const btn=$('sendBtn');btn.disabled=true;const now=new Date();const payload={type:state.type,latitude:state.lat,longitude:state.lng,accuracy:state.accuracy,description:$('description').value.trim(),reporter_id:'web-public',live_video:Boolean(state.stream)};try{if(!API_BASE||!navigator.onLine)throw new Error('offline');const r=await fetch(`${API_BASE}/api/incidents`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw Error();const incident=await r.json();state.incidentId=incident.id;if(state.evidence){const fd=new FormData();fd.append('file',state.evidence);const er=await fetch(`${API_BASE}/api/incidents/${state.incidentId}/evidence`,{method:'POST',body:fd});if(!er.ok)toast('Incident saved, but evidence upload failed.')}$('successText').textContent=`Your ${state.type.toLowerCase()} report is now in the live emergency API.`;$('successMeta').innerHTML=`<b>Incident ID:</b> <span>${incident.id}</span><br><b>Priority:</b> <span>${incident.priority}</span><br><b>Status:</b> <span>${incident.status}</span><br><b>Time:</b> <span>${new Date(incident.created_at).toLocaleString()}</span><br><b>GPS:</b> <span>${state.lat?`${state.lat.toFixed(6)}, ${state.lng.toFixed(6)}`:'Not available'}</span><br><b>Evidence:</b> <span>${state.evidence?state.evidence.name:'None'}</span>`;$('successDialog').showModal();await loadIncidents()}catch(e){const saved=await queueOffline(payload,state.evidence);if(saved){$('successText').textContent='Emergency saved offline. It will automatically upload when a connection returns.';$('successMeta').innerHTML=`<b>Mode:</b> <span>Offline queue</span><br><b>Time:</b> <span>${now.toLocaleString()}</span><br><b>GPS:</b> <span>${state.lat?`${state.lat.toFixed(6)}, ${state.lng.toFixed(6)}`:'Not available'}</span><br><b>Evidence:</b> <span>${state.evidence?state.evidence.name:'None'}</span>`;$('successDialog').showModal()}else{$('successText').textContent='Could not save this emergency locally. Please restore connectivity and retry.';$('successMeta').textContent=now.toLocaleString();$('successDialog').showModal()}}finally{btn.disabled=false}}
document.querySelectorAll('.incident').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.incident').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.type=btn.dataset.type}));
$('evidenceInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;if(f.size>25*1024*1024){toast('Please choose a file under 25 MB.');e.target.value='';return}showPreview(f)});$('locateBtn').addEventListener('click',getGPS);$('cameraBtn').addEventListener('click',startCamera);$('cameraStop').addEventListener('click',stopCamera);$('sendBtn').addEventListener('click',sendReport);$('dashboardBtn').addEventListener('click',()=>$('dashboard').scrollIntoView({behavior:'smooth'}));$('closeDialog').addEventListener('click',()=>{$('successDialog').close();$('reportCard').scrollIntoView({behavior:'smooth')});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')sendReport});window.addEventListener('online',flushOffline);window.addEventListener('beforeunload',()=>{if(state.watchId!==null)navigator.geolocation.clearWatch(state.watchId);stopCamera();if(state.ws)state.ws.close()});
renderQueue();loadIncidents();connectRealtime();setTimeout(()=>{if(navigator.geolocation)getGPS()},700);flushOffline();setInterval(flushOffline,15000);
